Added R package installation

diff --git a/bin/algorithm-install b/bin/algorithm-install
--- a/bin/algorithm-install
+++ b/bin/algorithm-install
@@ -37,7 +37,7 @@ RUBY_DIR="$HOME/.rbenv/versions/$RUBY_NUM_VER"
 
 # # # Install
 
-check_utils "rbenv find"
+check_utils "rbenv find R"
 check_log $SELF
 
 if [ "$OT_BRANCH" = "development" ]; then
@@ -58,6 +58,26 @@ install_ruby
 # fminer
 ( [ -n "`$FIND libfminer/ -name bbrc.so 2>/dev/null`" ] && [ -n "`$FIND libfminer/ -name last.so 2>/dev/null`" ] ) || . ./bin/fminer-install
 
+# R
+R_DONE=false
+mkdir "$R_DEST" >/dev/null 2>&1
+if [ ! -d "$R_DEST" ]; then
+  echo "Install directory '$R_DEST' is not available! Aborting..."
+  exit 1
+else
+  if ! rmdir "$R_DEST" >/dev/null 2>&1; then # if not empty this will fail
+    R_DONE=true
+  else
+    mkdir "$R_DEST" >/dev/null 2>&1
+  fi
+fi
+
+if ! $R_DONE; then
+  export R_LIBS="$R_DEST" # To install non-global
+  cmd="$R CMD BATCH bin/packs.R" && run_cmd "$cmd" "R packages"
+fi
+
+
 # self
 echo
 install_with_bundler
@@ -67,6 +87,14 @@ install_with_bundler
 if ! cat "$OT_CONFIG_DIR/config/$SELF.rb" | grep "four_store">/dev/null 2>&1; then echo '$four_store = { :uri => "http://localhost:9088", :user => "", :password => "" }' >> $OT_CONFIG_DIR/config/$SELF.rb; fi
 if ! cat "$OT_CONFIG_DIR/config/$SELF.rb" | grep "aa">/dev/null 2>&1; then echo '$aa = { :uri => nil }' >> $OT_CONFIG_DIR/config/$SELF.rb; fi
 if ! cat "$OT_DEFAULT_CONF" | grep "$SELF">/dev/null 2>&1; then echo '$algorithm = { :uri => "http://localhost:8081/algorithm" }' >> $OT_DEFAULT_CONF; fi
+if [ ! -f $R_CONF ]; then
+  echo "if echo \"\$R_LIBS\" | grep -v \"$R_DEST\">/dev/null 2>&1; then export R_LIBS=\"$R_DEST\"; fi" >> "$R_CONF"
+  echo "if ! [ -d \"$R_DEST\" ]; then echo \"\$0: '$R_DEST' is not a directory!\"; fi" >> "$R_CONF"
+  echo "R package destination stored in '$R_CONF'."
+  if ! grep "$R_CONF" $OT_UI_CONF >/dev/null 2>&1 ; then
+    echo ". \"$R_CONF\"" >> $OT_UI_CONF
+  fi
+fi
 
 if [ $SILENT = false ]; then
   notify
